nba_project_dbt:
  outputs:
    dev:
      dataset: 
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/keys/bq-creds.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: 
      threads: 1
      type: bigquery
  target: dev
